name: Build PKG

on:
  push:
    branches:
      - master

jobs:
  pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: pnpm i
      - run: pnpm build
      - run: npm i -g pkg
      - run: pkg .
      - run: ls -lh
      - uses: actions/upload-artifact@v2
        with:
          name: luogu-motaki-client-linux-${{ github.run_id }}
          path: luogu-motaki-client-linux
      - uses: actions/upload-artifact@v2
        with:
          name: luogu-motaki-client-macos-${{ github.run_id }}
          path: luogu-motaki-client-macos
      - uses: actions/upload-artifact@v2
        with:
          name: luogu-motaki-client-win-${{ github.run_id }}
          path: luogu-motaki-client-win.exe
